### PR TITLE
Revert "add AUTHORS and ChangeLog files"

### PR DESCRIPTION
**Pull request by emonty**
AUTHORS and ChangeLog are generated by pbr every time you install
the software or make an sdist tarball. The idea is that git is
the source of truth, and the only time these files are needed is
in in a source tarball when git isn't available. Committing them
will mean you'll have new local content on every commit, which
will likely get ... annoying.

This reverts commit 30312b1260f996ddf3ea771ae8bc89483a66dd08.

### CODE REVIEW

**Comment by elmiko** [comment]
i knew they got regenerated by pbr, but i had decided to check them in because i think seeing the change log is actually useful for some folks.

**Comment by elmiko** [comment]
i can see the wisdom in removing them, and definitely don't want to commit on each change. i was thinking that the ChangeLog would be useful to commit at each release just as a quick way to view what had changed since last time.

**Comment by emonty** [comment]
Ah - nod. That makes sense.

In retrospect, now that reno exists, I'm a bit sad that we generate those files in the first place... but such is life.

**Comment by elmiko** [comment]
> In retrospect, now that reno exists, I'm a bit sad that we generate those files in the first place... but such is life.

i can totally dig that, and while i do like reno it seems like overkill for this project. but maybe i should re-evaluate.

**Comment by elmiko** [comment]
i've added a pr for a contributing doc to help make my reasoning a little more transparent (#12). i'm going to close this, thanks again for the contributions and advice @emonty =)

**Pull request closed without merging**
